set(APP_DISPLAY_NAME "红果鉴")
set(APP_EXECUTABLE_NAME "hongguojian.exe")
foreach(ENTRY IN LISTS FLUTTER_TOOL_ENVIRONMENT)
  if(ENTRY MATCHES "^DART_DEFINES=(.*)$")
    string(REPLACE "," ";" APP_DART_DEFINES "${CMAKE_MATCH_1}")
    foreach(DEFINE IN LISTS APP_DART_DEFINES)
      if(DEFINE STREQUAL "QUxMX1NPVVJDRVM9dHJ1ZQ==")
        set(APP_DISPLAY_NAME "真果鉴")
        set(APP_EXECUTABLE_NAME "zhenguojian.exe")
      elseif(DEFINE STREQUAL "QUxMX1NPVVJDRVM9ZmFsc2U=")
        set(APP_DISPLAY_NAME "红果鉴")
        set(APP_EXECUTABLE_NAME "hongguojian.exe")
      endif()
    endforeach()
  endif()
endforeach()
